kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag-aug16-vllm-1-dsp-job-rolebinding
subjects:
  - kind: ServiceAccount
    name: rag-aug16-vllm-1-dsp-job
    namespace: rag-aug16-vllm-1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag-aug16-vllm-1-dsp-job-role